### ISSUE TITLE
pattern ui/dist/*: no matching files found

### ISSUE THREAD

**Issue by ayoub-tl** [iximiuz/kexp#3]
I am trying to run kexp locally on machine, but when, running the backend service using make back-run-dev it return this error 
$ make back-run-dev
go run /home/ubuntu/kexp/main.go --host 0.0.0.0 --port 8090
main.go:65:12: pattern ui/dist/*: no matching files found
make: *** [Makefile:9: back-run-dev] Error 1

does anyone have an idea ? the ui/dist folder doesn't exist.
Thanks

**Comment by iximiuz** [comment]
Oh, good catch! Running `make build-dev` before `make back-run-dev` mitigates the issue, that's why I didn't spot it earlier. [Should be fixed now](https://github.com/iximiuz/kexp/commit/93675c9f5a494ec04249f7d9d56e1eb53310ee3c). Thanks for reporting!
